projectName: jquery-mutation-summary
projectUrl: http://joelpurra.github.com/jquery-mutation-summary
projectGithub: https://github.com/joelpurra/jquery-mutation-summary

googleAnalyticsAccountId: UA-29171100-1